name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ollama-proxy-plugin
          path: build/distributions/*.zip
